### PR TITLE
Updated docker to 19.03.1 and golang to 1.12.5

### PR DESCRIPTION
**Pull request by lareeth**

### CODE REVIEW

**Comment by jmaitrehenry** [comment]
Love to see it available as some bugs exist in 18.09 and some windows specific functionality.

**Comment by CollinChaffin** [comment]
Thanks @lareeth I had an issue open but Stefan has been busy and didn't get to it so I too appreciate the PR and build!

**Comment by lareeth** [comment]
@StefanScherer let me know once you have added the docker binary to releases

**Comment by lareeth** [comment]
The binary is version 0.0.0-dev. I think there's an issue with version in the source code

**Pull request merged**
