### PR TITLE
Updated docker to 19.03.12 and golang to 1.13.12

### PR DESCRIPTION
**Pull request by carlitorendon**
Used this tag to obtain versions:
https://github.com/docker/cli/releases/tag/v19.03.12

### CODE REVIEW

**Comment by StefanScherer** [comment]
Oh, there is no `microsoft/windowsservercore:latest` tag, MSFT has removed the `latest` tag long time ago. Maybe AppVeyor got it for convenience reasons. Should be `ltsc2019` nowadays.

**Comment by carlitorendon** [comment]
> Oh, there is no `microsoft/windowsservercore:latest` tag, MSFT has removed the `latest` tag long time ago. Maybe AppVeyor got it for convenience reasons. Should be `ltsc2019` nowadays.

Hello @StefanScherer thanks for getting back to me. Anything on my side I can do to help to transition the versions?

**Comment by carlitorendon** [comment]
> Oh, there is no `microsoft/windowsservercore:latest` tag, MSFT has removed the `latest` tag long time ago. Maybe AppVeyor got it for convenience reasons. Should be `ltsc2019` nowadays.

Hello @StefanScherer thank you for pointing that out. After playing lottery with the windows host, it turned out to be ltsc2016. 

Now the process is dying on this line: 
`RUN powershell iex(iwr -useb https://chocolatey.org/install.ps1)`

claiming it can't a trusted SSL connection to chocolatey.org... 

I tried to add a `-SkipCertificateCheck` flag just to realize it is only supported in PowerShell 7. Of course ltsc2016 is running stock 5.0 (where the flag is not allowed). 

Any ideas 🤔?

**Comment by StefanScherer** [comment]
Oh, indeed ltsc2016. Well that can be fixed by updating the AppVeyor image.

https://www.appveyor.com/docs/windows-images-software/#docker

In the appveyor.yml use `Visual Studio 2019` which is installed on a Windows Server 2019. Docker has evolved a lot since Server 2016 came out, I encourage to use the newest OS available.

**Comment by carlitorendon** [comment]
> Oh, indeed ltsc2016. Well that can be fixed by updating the AppVeyor image.
> 
> https://www.appveyor.com/docs/windows-images-software/#docker
> 
> In the appveyor.yml use `Visual Studio 2019` which is installed on a Windows Server 2019. Docker has evolved a lot since Server 2016 came out, I encourage to use the newest OS available.

Hello @StefanScherer thank you for the tip! New to AppVeyor. It seems like it passed ok.

**Comment by StefanScherer** [comment]
@carlitorendon a new github release is live. 😀

**Comment by carlitorendon** [comment]
> @carlitorendon a new github release is live. 😀

@StefanScherer thank you for pointing me in the right direction!

**Pull request merged**
